### ISSUE TITLE
Implement Newsletter Subscription Functionality for Users on the TDC Portal

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#108]
As a user of the TDC portal, I want the ability to join the TDC newsletter powered by their newsletter provider, so that I can stay informed about updates, events, and news from the Transport Data Commons. 

## Tasklist (TBD - updated by the developer)
* [x] add button that links to given url for newsletter signup
* [x] Write documentation
* [x] Write integration tests

## Acceptance Criteria
Given that I am on every publicly available page of the portal, 
* [ ] I want a to be able to provide my email and be added to the TDC newsletter.
* [ ] Upon the submission of the form, a confirmation message should appear, acknowledging the subscription and informing me to check their email for verification.

**Comment by Verena205** [comment]
Instead of having the sign-up option integrated in the website, we should have a button that redirects to a page for the sign up. It should be structured similary to the current structure: ![Image](https://github.com/user-attachments/assets/41fbf765-640d-42af-a3ff-3cf4e3a66631). After this, there would be a button saying "Join Newsletter": ![Image](https://github.com/user-attachments/assets/98bc61f6-7297-47f6-97f7-7c2bdc9f092b)

No privacy policies would be shown so we remove this part: ![Image](https://github.com/user-attachments/assets/7a65b7cc-6a46-4db2-85c6-b1ea6e327ce9)

**Comment by Verena205** [comment]
Link will be provided once it has been fixed

**Comment by Verena205** [comment]
here is the link: https://civicrm.changing-transport.org/form/tdci-newsletter

**Comment by Uchechukwu-Onye-Igbo** [comment]
> here is the link: https://civicrm.changing-transport.org/form/tdci-newsletter

Thank you. We will update it shortly.

cc @willy1989cv

**Comment by willy1989cv** [comment]
Done. @Verena205 @Uchechukwu-Onye-Igbo

**Comment by willy1989cv** [comment]
Doc: https://github.com/transport-data/tdc-data-portal/blob/main/docs/newsletter
Test: https://github.com/transport-data/tdc-data-portal/actions/runs/11443191415/job/31835267784#step:14:1427
