### ISSUE TITLE
Implement GitHub SSO Signup Flow for Invited Users with Organization Association

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#184]
When a non-existent user is invited to join an organization on the TDC portal, they should receive an email with a link to signup to the portal via GitHub SSO, so that they can easily join the organization (with the role assigned them upon the invite), even if their GitHub email differs from the invitation email.

## Tasklist (TBD - updated by the developer)
* [add tasks]

## Acceptance Criteria 
Given that I am editing an organisation and then invite a user who is not already registered in the portal,
* [x] they should get an email to join the platform
* [x] once they follow the link, they will be led to create an account using GitHub SSO
* [x] when they signup to the platform, they should join the organisation that they were originally invited to without having to be specially added separately.
* [x] their role in the organisation after they join should be the exact one they were originally invited as.

**Comment by nicolas-becker** [comment]
Hi @demenech, I have been replicating this use case and observed the expected behavior you described in the sprint review:
![Image](https://github.com/user-attachments/assets/340715bb-0122-45f9-8fa8-f0447ebec7e9)

The problem I am seeing is that I am now unable to click "Next" as the "Select Organization" field is required but I cannot select the organization I was invited to. The only option to move forward is by skipping, which from a UX perspective this is not optimal.

I see two options to fix this, either:
- a) making the "Select Organization" field optional, which would affect the usual Sign-Up flow (without previous invite), as we would open the floor to users without affiliation to organizations.
- b) (strongly preferred but maybe more difficult to implement) giving the option to select multiple organizations at this stage. Apart from being a realistic use case for users with multiple affiliation, this would make the process easier and more intuitive for the invited user. The org he/she was invited to would be preselected, but the user could still opt to select more orgs.

Looking forwards to hear your thoughts on this. Thanks!

**Comment by Uchechukwu-Onye-Igbo** [comment]
> * b) (strongly preferred but maybe more difficult to implement) giving the option to select multiple organizations at this stage. Apart from being a realistic use case for users with multiple affiliation, this would make the process easier and more intuitive for the invited user. The org he/she was invited to would be preselected, but the user could still opt to select more orgs.

Hello @nicolas-becker, we have decided a way to fix this. It is similar to your option A above. Kindly note that we will not be following option B at all because that is out of scope and very complicated. We worked according to the design provided and this was no in there. 

Thank you.

**Comment by nicolas-becker** [comment]
Hi @Uchechukwu-Onye-Igbo thanks for the feedback and for pointing out the difficulty level of the two options. I understand that the second option is hard to implement, so dropping it is fine. Could you please provide some further explanation on the specifics of the selected approach? Thanks

**Comment by demenech** [comment]
hi @nicolas-becker 

In summary:

- We'll tweak the "find organization" message to inform the user he's already a member of an organization, and he can choose another organization only if he wants to request to be a member of another organization besides the one he's already a member of.
- The current user organization will be pre-selected, and the user will be able to click "next" (which won't trigger any email notification as the user only sees this when he was directly invited to an org, which means that the org admin doesn't have to approve the request)

**Comment by nicolas-becker** [comment]
Hi @Uchechukwu-Onye-Igbo @demenech I just had a look at the new sign-in process and it looks good, thank you! 

I just noticed that the final step (invite friends, etc..) still seems to be required:
![Image](https://github.com/user-attachments/assets/f027ec94-535b-4304-8615-9a0f65963f5e)
Is it still possible to change this to optional, as agreed? Thanks!

**Comment by Uchechukwu-Onye-Igbo** [comment]
> Hi @Uchechukwu-Onye-Igbo @demenech I just had a look at the new sign-in process and it looks good, thank you! 
> 
> I just noticed that the final step (invite friends, etc..) still seems to be required:
> ![Image](https://github.com/user-attachments/assets/f027ec94-535b-4304-8615-9a0f65963f5e)
> Is it still possible to change this to optional, as agreed? Thanks!

This is a skippable step, so it's not required.

However we implemented it in a way that makes the email field required if a user clicks to enter a message in the message field
